# -*- coding: utf-8 -*-
"""k_means_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izj4u-Hc_sxgAhJer37NYJSS9bLEiw3d
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

data = pd.read_csv('Mall_Customers.csv')
data.head()

X=data[['Annual Income (k$)', 'Spending Score (1-100)']]

plt.figure(figsize=(10,5))
plt.scatter(X['Annual Income (k$)'], X['Spending Score (1-100)'], color= 'blue', s=50)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()

inertia_values = []

for k in range(1,11):
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(X)
    inertia_values.append(model.inertia_)

plt.figure(figsize=(10,5))
plt.plot(range(1,11), inertia_values, marker='o', linestyle='--')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show ()

model=KMeans(n_clusters=5, random_state=42)
clusters = model.fit_predict(X)

plt.figure(figsize=(10,5))
plt.scatter(X['Annual Income (k$)'], X['Spending Score (1-100)'], c=clusters, cmap='viridis', s= 50)
plt.scatter(model.cluster_centers_[:,0], model.cluster_centers_[:,1], color='red', marker='X', s=200)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()