# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IaqKqGQ6w7XYLaFc2kpaWXwclMrxuwu7
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

X,y_true = make_blobs(n_samples=300, centers=3, random_state= 42)
X.shape
plt.scatter(X[:,0], X[:,1], cmap='rainbow')
plt.show()

k=3

random_indices = np.random.choice(len(X), k, replace= False)
centroids = X[random_indices]
print(centroids)

def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

def assign_clusters(X, centroids):
    clusters = []

    for point in X:
        distances = [euclidean_distance(point, centroid) for centroid in centroids]
        cluster = np.argmin(distances)
        clusters.append(cluster)

    return np.array(clusters)

def update_centroids(X, clusters, k):
  new_centroids = []

  for i in range(k):
    points = X[clusters == i]
    centroid = np.mean(points, axis=0)
    new_centroids.append(centroid)

  return np.array(new_centroids)

iteration = 10

for i in range(iteration):
  print(f"Iteration: {i+1}")
  clusters = assign_clusters(X, centroids)
  centroids = update_centroids(X, clusters, k)


print("Final Centroid")
print(centroids)

plt.scatter(X[:,0], X[:,1], c= clusters, cmap='viridis')
plt.scatter(centroids[:,0], centroids[:,1], c='red', marker='x', s=200)
plt.title("Final K-means clusters")
plt.show()

from sklearn.cluster import KMeans
model = KMeans(n_clusters=3, random_state = 42)
model.fit(X)

plt.scatter(X[:,0], X[:,1], c= model.labels_, cmap='viridis')
plt.scatter(model.cluster_centers_[:,0], model.cluster_centers_[:,1], color='red', marker='x', s = 200)
plt.title("Final K-means clusters")
plt.show()