# -*- coding: utf-8 -*-
"""Apriori_using_Library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yq57dKqdjT6fJlrMEO_Ts4LYjzdjt26u
"""

import pandas as pd
import itertools

#Step 1: Create a dataset

data = {
    "TID": [1,2,3,4,5,6,7,8,9,10],
    "Items": [
        "Milk;Bread",
        "Milk;Diaper;Beer;Eggs",
        "Milk;Bread;Diaper;Beer",
        "Bread;Milk;Diaper;Beer",
        "Bread;Milk;Diaper;Coke",
        "Milk;Bread;Butter",
        "Bread;Butter;Jam",
        "Milk;Diaper;Beer",
        "Milk;Bread;Diaper",
        "Bread;Beer"
    ]
}
min_support = 2

df = pd.DataFrame(data)
df

df.to_csv("transaction.csv", index=False)
print("csv file created successfully")

#Step 2: Load csv file
df=pd.read_csv("transaction.csv")
print("original csv file")
print(df)

transaction = df['Items'].apply(lambda x: x.split(';')).tolist()
transaction

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_data = te.fit(transaction).transform(transaction)

df_encoded = pd.DataFrame(te_data, columns=te.columns_)
print(df_encoded)

frequent_itemsets = apriori(df_encoded, min_support=0.3, use_colnames=True)
print(frequent_itemsets)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)
print(rules)

sorted_rules = rules.sort_values(by='lift', ascending=False)
print(sorted_rules)

