# -*- coding: utf-8 -*-
"""Apriori_without_library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hcBFW2shnSQFOLE3vDcvzcrrdgMzXFY2
"""

import pandas as pd
import itertools

dataset = [
    ['Milk', 'Bread'],
    ['Milk', 'Diaper', 'Beer', 'Eggs'],
    ['Milk', 'Bread', 'Diaper', 'Beer'],
    ['Bread', 'Milk', 'Diaper', 'Beer'],
    ['Bread', 'Milk', 'Diaper', 'Coke']
]

minimum_support = 2

# Function to calculate support count

def get_support_count(itemset, transactions):
  count = 0

  for transaction in transactions:
    if set(itemset).issubset(set(transaction)):
      count += 1

  return count


items = set(item for transaction in dataset for item in transaction)
frequent_itemsets = []
L1 = []

for item in items:
  support = get_support_count([item], dataset)
  if support >= minimum_support:
    L1.append(([item], support))

frequent_itemsets.extend(L1)
print("Frequent 1 - iemsets:")
print(L1)

k=2

current_L = [item[0] for item in L1]

while current_L:
  candidates = list(itertools.combinations(set(itertools.chain(*current_L)), k))

  LK=[]

  for candidate in candidates:
    support = get_support_count(candidate, dataset)
    if support >= minimum_support:
      LK.append((list(candidate), support))

  if not LK:
    break

  frequent_itemsets.extend(LK)

  current_L = [item[0] for item in LK]
  print(f"\n Frequent {k}-itemsets:")
  print(LK)

  k+=1
  print("\n All Frequent Itemsets")
  for itemset in frequent_itemsets:
    print(itemset)

