# -*- coding: utf-8 -*-
"""Apriori_using_map_reduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msbw1jGf3altgJkwNsb8MgmqfU-Rw8Yy
"""

!java -version

!wget https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
!tar -xzf hadoop-3.3.6.tar.gz

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["HADOOP_HOME"] = "/content/hadoop-3.3.6"
os.environ["PATH"] += ":/content/hadoop-3.3.6/bin:/content/hadoop-3.3.6/sbin"

!grep -n JAVA_HOME /content/hadoop-3.3.6/etc/hadoop/hadoop-env.sh

!sed -i '/JAVA_HOME/d' /content/hadoop-3.3.6/etc/hadoop/hadoop-env.sh

!hadoop version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hadoop-3.3.6/etc/hadoop/yarn-site.xml
# <configuration>
# 
# <property>
#   <name>yarn.nodemanager.aux-services</name>
#   <value>mapreduce_shuffle</value>
# </property>
# 
# <property>
#   <name>yarn.nodemanager.auxservices.mapreduce.shuffle.class</name>
#   <value>org.apache.hadoop.mapred.ShuffleHandler</value>
# </property>
# 
# </configuration>

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hadoop-3.3.6/etc/hadoop/core-site.xml
# <configuration>
#   <property>
#     <name>fs.defaultFS</name>
#     <value>hdfs://localhost:9000</value>
#   </property>
# </configuration>
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hadoop-3.3.6/etc/hadoop/hdfs-site.xml
# <configuration>
#   <property>
#     <name>dfs.replication</name>
#     <value>1</value>
#   </property>
# </configuration>
#

!readlink -f $(which java)

!echo -e "\nexport HDFS_NAMENODE_USER=root\nexport HDFS_DATANODE_USER=root\nexport HDFS_SECONDARYNAMENODE_USER=root" \
>> /content/hadoop-3.3.6/etc/hadoop/hadoop-env.sh

!hdfs namenode -format

!hdfs --daemon start namenode

!hdfs --daemon start datanode

!hdfs --daemon start secondarynamenode

!jps

!hdfs dfs -mkdir /ap



# Commented out IPython magic to ensure Python compatibility.
# %%writefile mapper.py
# #!/usr/bin/env python3
# import sys
# 
# #loops reads each transaction one by one
# for line in sys.stdin:
#     items = line.strip().split(",")
#     for item in items:
#       item = item.strip()
#       print(f"{item}\t1")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile reducer.py
# #!/usr/bin/env python3
# import sys
# 
# current_item = None
# 
# current_count = 0
# minimum_support = 1
# 
# for line in sys.stdin:
#     item, count = line.strip().split("\t")
#     count = int(count)
# 
#     if current_item == item:
#         current_count += count
#     else:
#         if current_item and current_count >= minimum_support:
#             print(f"{current_item}\t{current_count}")
# 
#         current_item = item
#         current_count = count
# if current_item and current_count >= minimum_support:
#     print(f"{current_item}\t{current_count}")

!chmod +x mapper.py reducer.py

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
# export HADOOP_HOME=/content/hadoop-3.3.6
# export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
# 
# hdfs dfs -put -f transactions.csv /ap/

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
# export HADOOP_HOME=/content/hadoop-3.3.6
# export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
# 
# hdfs dfs -rm -r -f /ap/output
# 
# hadoop jar $HADOOP_HOME/share/hadoop/tools/lib/hadoop-streaming-*.jar \
# -files mapper.py,reducer.py \
# -input /ap/transactions.csv \
# -output /ap/output \
# -mapper "python3 mapper.py" \
# -reducer "python3 reducer.py"
#

!hdfs dfs -ls /ap

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
# export HADOOP_HOME=/content/hadoop-3.3.6
# export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
# 
# hdfs dfs -cat /ap/output/part-00000

