# -*- coding: utf-8 -*-
"""hadoop_installation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2R-DKkL1Ok62714EeYKzsGCOn2XyBcm
"""

!java -version

!sudo apt-get install openjdk-8-jdk -y
!java -version

!wget https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
!tar -xzf hadoop-3.3.6.tar.gz

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["HADOOP_HOME"] = "/content/hadoop-3.3.6"
os.environ["PATH"] += ":/content/hadoop-3.3.6/bin:/content/hadoop-3.3.6/sbin"

!hadoop version

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hadoop-3.3.6/etc/hadoop/core-site.xml
# <configuration>
#   <property>
#     <name>fs.defaultFS</name>
#     <value>hdfs://localhost:9000</value>
#   </property>
# </configuration>
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hadoop-3.3.6/etc/hadoop/hdfs-site.xml
# <configuration>
#   <property>
#     <name>dfs.replication</name>
#     <value>1</value>
#   </property>
# </configuration>
#

!readlink -f $(which java)

!sed -i 's|# export JAVA_HOME=.*|export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64|' \
/content/hadoop-3.3.6/etc/hadoop/hadoop-env.sh

!echo -e "\nexport HDFS_NAMENODE_USER=root\nexport HDFS_DATANODE_USER=root\nexport HDFS_SECONDARYNAMENODE_USER=root" \
>> /content/hadoop-3.3.6/etc/hadoop/hadoop-env.sh

!hdfs namenode -format

!hdfs --daemon start namenode

!hdfs --daemon start datanode

!hdfs --daemon start secondarynamenode

!jps

!hdfs dfs -mkdir /lab

!echo "Big data" > test.txt

!hdfs dfs -put test.txt /lab

!hdfs dfs -ls /lab

!hdfs dfs -cat /lab/test.txt