# -*- coding: utf-8 -*-
"""Fp_growth_wihout_using_library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xi8Bs6Fgtk7ucNHIUyHPAB8RivCpvNg2
"""

dataset = [
    ['E', 'K', 'M', 'N', 'O', 'Y'],
    ['D', 'E', 'K', 'N', 'O', 'Y'],
    ['A', 'E', 'K', 'M'],
    ['C', 'K', 'M', 'U', 'Y'],
    ['C', 'E', 'I', 'K', 'O']
]

#Pruning using the min support
min_support = 3

# first database scan - count frequency
from collections import defaultdict
item_count  = defaultdict(int)

for transaction in dataset:
    for item in transaction:
        item_count[item] += 1

# prune infrequent items
item_count = {item: count for item, count in item_count.items() if count >= min_support}

print("frequent 1-itemsets", item_count)

sorted_items = sorted(item_count, key=item_count.get, reverse=True)
print(sorted_items)

filtered_dataset = []
for transaction in dataset:
  filtered = [item for item in transaction if item in item_count]
  filtered.sort(key=lambda x: item_count[x], reverse=True)
  filtered_dataset.append(filtered)

print(filtered_dataset)

class FPNode:
    def __init__(self, item, count, parent):
        self.item = item          # item name
        self.count = count        # frequency
        self.parent = parent      # parent node
        self.children = {}        # child nodes
        self.link = None          # node link (header table)


# ---------------------------
# STEP 5: BUILD FP-TREE
# ---------------------------

def build_tree(dataset):
    root = FPNode(None, 1, None)
    header_table = {}

    for transaction in dataset:
        current_node = root

        for item in transaction:
            if item in current_node.children:
                current_node.children[item].count += 1
            else:
                new_node = FPNode(item, 1, current_node)
                current_node.children[item] = new_node

                # Maintain header table links
                if item in header_table:
                    current = header_table[item]
                    while current.link:
                        current = current.link
                    current.link = new_node
                else:
                    header_table[item] = new_node

            current_node = current_node.children[item]

    return root, header_table


tree_root, header_table = build_tree(filtered_dataset)


# ---------------------------
# STEP 6: CONDITIONAL PATTERN BASE
# ---------------------------

def find_prefix_path(base_item, header_table):
    paths = []
    node = header_table[base_item]

    while node:
        path = []
        parent = node.parent

        # Trace path to root
        while parent and parent.item:
            path.append(parent.item)
            parent = parent.parent

        # Add path according to node count
        for _ in range(node.count):
            if path:
                paths.append(path)

        node = node.link

    return paths

def mine_tree(header_table, prefix, frequency_patterns):

  for base_item in header_table:
    new_pattern = prefix.copy()
    new_pattern.add(base_item)
    frequent_patterns.append(new_pattern)

    conditional_pattern_base = find_prefix_path(base_item, header_table)
    conditional_tree, conditional_header = build_tree(conditional_pattern_base)

    if conditional_header:
      mine_tree(conditional_header, new_pattern, frequency_patterns)

frequent_patterns = []
mine_tree(header_table, set(), frequent_patterns)
print("frequent patterns")
for pattern in frequent_patterns:
  print(pattern)

import pandas as pd
import random

items = [
    ['Milk', 'Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Milk', 'Bread', 'Butter'],
    ['Bread', 'Butter'],
    ['Milk', 'Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Beer', 'Diaper'],
    ['Beer', 'Diaper'],
    ['Beer', 'Diaper'],
    ['Milk', 'Bread', 'Butter']
]

transactions = [
    ['Milk', 'Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Milk', 'Bread', 'Butter'],
    ['Bread', 'Butter'],
    ['Milk', 'Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Beer', 'Diaper'],
    ['Beer', 'Diaper'],
    ['Beer', 'Diaper'],
    ['Milk', 'Bread', 'Butter']
]

print(transactions[:5])

df_tranasaction =pd.DataFrame({
    'transaction': [",".join(t) for t in transactions]
})

df_tranasaction.to_csv("data.csv", index = False)

data= pd.read_csv("data.csv")
data.head()

transaction_list = data["transaction"].apply(lambda x: x.split(",")).tolist()
transaction_list

from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()

te_array = te.fit(transaction_list).transform(transaction_list)

df = pd.DataFrame(te_array, columns = te.columns_)
df.head()

from mlxtend.frequent_patterns import fpgrowth

frequent_itemsets = fpgrowth (df, min_support=0.2, use_colnames=True)
frequent_itemsets = frequent_itemsets.sort_values(by='support', ascending=False)
frequent_itemsets

from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric= "confidence", min_threshold=0.5)

rules = rules.sort_values(by='confidence', ascending=False)
rules

