# -*- coding: utf-8 -*-
"""Fp_growth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYw_8IfVcx0BQdPZ3-vxY3nmprFKe6Rm
"""

!pip install mlxtend

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

from mlxtend.frequent_patterns import association_rules

dataset = [
    ['E', 'K', 'M', 'N', 'O', 'Y'],
    ['D', 'E', 'K', 'N', 'O', 'Y'],
    ['A', 'E', 'K', 'M'],
    ['C', 'K', 'M', 'U', 'Y'],
    ['C', 'E', 'I', 'K', 'O', 'O']
]
dataset

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
frequent_itemsets

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules

import random

items = [
    "Milk", "Bread", "Butter", "Cheese", "Eggs",
    "Diaper", "Beer", "Coke", "Chips", "Chicken",
    "Rice", "Dal", "Oil", "Sugar", "Salt"
]

transactions = []

for i in range(30):
  transaction_size = random.randint(2,6)
  transaction =  random.sample(items, transaction_size)
  transactions.append(transaction)

df_transactions = pd.DataFrame({
    "Transaction": [",".join(t) for t in transactions]
})
df_transactions.to_csv("supermarket_data.csv", index=False)
df_transactions

data = pd.read_csv("supermarket_data.csv")
data.head()

transaction_list = data["Transaction"].apply(lambda x: x.split(",")).tolist()
transaction_list

from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_array=te.fit(transaction_list).transform(transaction_list)
df=pd.DataFrame(te_array, columns=te.columns_)
df

from mlxtend.frequent_patterns import fpgrowth
frequent_itemsets = fpgrowth(df, min_support=0.2, use_colnames=True)
frequent_itemsets.sort_values("support", ascending=False)

from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
rules.sort_values("lift", ascending=False)

